// Package pb contains hand-written Go stubs for api/proto/classifier/v1/classifier.proto.
//
// These types and the client wrapper are intentionally not generated by protoc
// so the project can avoid a protobuf build-time dependency while still
// speaking standard gRPC to a remote classifier.
package pb

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// ClassifierClient is the gRPC client for the Classifier service.
type ClassifierClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

// classifierClient is a concrete wrapper around *grpc.ClientConn.
type classifierClient struct {
	cc *grpc.ClientConn
}

// NewClassifierClient returns a ClassifierClient backed by conn.
func NewClassifierClient(conn *grpc.ClientConn) ClassifierClient {
	return &classifierClient{cc: conn}
}

// Classify delegates to the Classify RPC.
func (c *classifierClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, "/classifier.v1.Classifier/Classify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ping delegates to the Ping RPC.
func (c *classifierClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/classifier.v1.Classifier/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Info delegates to the Info RPC.
func (c *classifierClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/classifier.v1.Classifier/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierServer is the gRPC server interface for the Classifier service.
type ClassifierServer interface {
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedClassifierServer()
}

// UnimplementedClassifierServer provides a default implementation for forward compatibility.
type UnimplementedClassifierServer struct{}

func (UnimplementedClassifierServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, fmt.Errorf("method Classify is not implemented")
}

func (UnimplementedClassifierServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, fmt.Errorf("method Ping is not implemented")
}

func (UnimplementedClassifierServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, fmt.Errorf("method Info is not implemented")
}

func (UnimplementedClassifierServer) mustEmbedUnimplementedClassifierServer() {}

// RegisterClassifierServer registers the server with the gRPC server.
func RegisterClassifierServer(s *grpc.Server, srv ClassifierServer) {
	s.RegisterService(&Classifier_ServiceDesc, srv)
}

// Classifier_ServiceDesc is the service descriptor used by RegisterClassifierServer.
var Classifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classifier.v1.Classifier",
	HandlerType: (*ClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _Classifier_Classify_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Classifier_Ping_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Classifier_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classifier.proto",
}

func _Classifier_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/classifier.v1.Classifier/Classify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classifier_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/classifier.v1.Classifier/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classifier_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/classifier.v1.Classifier/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// messageNoReflect is a minimal protoreflect.Message implementation for
// hand-written proto messages. It satisfies proto.Message but does not support
// reflection. This is enough for gRPC/protobuf marshaling to work.
type messageNoReflect struct{}

func (messageNoReflect) Descriptor() protoreflect.MessageDescriptor {
	return nil
}

func (messageNoReflect) Type() protoreflect.MessageType {
	return nil
}

func (messageNoReflect) New() protoreflect.Message {
	return nil
}

func (messageNoReflect) Interface() protoreflect.ProtoMessage {
	return nil
}

func (messageNoReflect) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {}

func (messageNoReflect) Has(fd protoreflect.FieldDescriptor) bool { return false }

func (messageNoReflect) Clear(fd protoreflect.FieldDescriptor) {}

func (messageNoReflect) Get(fd protoreflect.FieldDescriptor) protoreflect.Value {
	return protoreflect.Value{}
}

func (messageNoReflect) Set(fd protoreflect.FieldDescriptor, v protoreflect.Value) {}

func (messageNoReflect) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	return protoreflect.Value{}
}

func (messageNoReflect) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	return protoreflect.Value{}
}

func (messageNoReflect) WhichOneof(od protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	return nil
}

func (messageNoReflect) GetUnknown() protoreflect.RawFields { return nil }

func (messageNoReflect) SetUnknown(fields protoreflect.RawFields) {}

func (messageNoReflect) IsValid() bool { return false }

// ClassifyRequest is the request to Classify.
type ClassifyRequest struct {
	messageNoReflect
	Groups []*TraceGroup
}

// Reset implements proto.Message.
func (m *ClassifyRequest) Reset() { *m = ClassifyRequest{} }

// String implements proto.Message.
func (m *ClassifyRequest) String() string { return fmt.Sprintf("ClassifyRequest{groups:%d}", len(m.Groups)) }

// ProtoMessage implements proto.Message.
func (*ClassifyRequest) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *ClassifyRequest) ProtoReflect() protoreflect.Message { return nil }

// TraceGroup is a group of related traces.
type TraceGroup struct {
	messageNoReflect
	Traces []*Trace
}

// Reset implements proto.Message.
func (m *TraceGroup) Reset() { *m = TraceGroup{} }

// String implements proto.Message.
func (m *TraceGroup) String() string { return fmt.Sprintf("TraceGroup{traces:%d}", len(m.Traces)) }

// ProtoMessage implements proto.Message.
func (*TraceGroup) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *TraceGroup) ProtoReflect() protoreflect.Message { return nil }

// Trace is a single kernel-level event.
type Trace struct {
	messageNoReflect
	PID          int32
	Syscall      string
	Args         string
	ReturnValue  int64
	TimestampNs  int64
}

// Reset implements proto.Message.
func (m *Trace) Reset() { *m = Trace{} }

// String implements proto.Message.
func (m *Trace) String() string { return fmt.Sprintf("Trace{syscall:%s}", m.Syscall) }

// ProtoMessage implements proto.Message.
func (*Trace) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *Trace) ProtoReflect() protoreflect.Message { return nil }

// ClassifyResponse is the response from Classify.
type ClassifyResponse struct {
	messageNoReflect
	Flows []*Flow
}

// Reset implements proto.Message.
func (m *ClassifyResponse) Reset() { *m = ClassifyResponse{} }

// String implements proto.Message.
func (m *ClassifyResponse) String() string { return fmt.Sprintf("ClassifyResponse{flows:%d}", len(m.Flows)) }

// ProtoMessage implements proto.Message.
func (*ClassifyResponse) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *ClassifyResponse) ProtoReflect() protoreflect.Message { return nil }

// Flow is a classified semantic flow.
type Flow struct {
	messageNoReflect
	ID          string
	Intent      string
	Phase       string
	Description string
	Outcome     string
	Confidence  float64
	TraceIDs    []string
	StartTime   int64
	EndTime     int64
	DurationNs  int64
}

// Reset implements proto.Message.
func (m *Flow) Reset() { *m = Flow{} }

// String implements proto.Message.
func (m *Flow) String() string { return fmt.Sprintf("Flow{id:%s}", m.ID) }

// ProtoMessage implements proto.Message.
func (*Flow) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *Flow) ProtoReflect() protoreflect.Message { return nil }

// PingRequest is the request to Ping.
type PingRequest struct {
	messageNoReflect
}

// Reset implements proto.Message.
func (m *PingRequest) Reset() { *m = PingRequest{} }

// String implements proto.Message.
func (m *PingRequest) String() string { return "PingRequest{}" }

// ProtoMessage implements proto.Message.
func (*PingRequest) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *PingRequest) ProtoReflect() protoreflect.Message { return nil }

// PingResponse is the response from Ping.
type PingResponse struct {
	messageNoReflect
}

// Reset implements proto.Message.
func (m *PingResponse) Reset() { *m = PingResponse{} }

// String implements proto.Message.
func (m *PingResponse) String() string { return "PingResponse{}" }

// ProtoMessage implements proto.Message.
func (*PingResponse) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *PingResponse) ProtoReflect() protoreflect.Message { return nil }

// InfoRequest is the request to Info.
type InfoRequest struct {
	messageNoReflect
}

// Reset implements proto.Message.
func (m *InfoRequest) Reset() { *m = InfoRequest{} }

// String implements proto.Message.
func (m *InfoRequest) String() string { return "InfoRequest{}" }

// ProtoMessage implements proto.Message.
func (*InfoRequest) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *InfoRequest) ProtoReflect() protoreflect.Message { return nil }

// InfoResponse is the response from Info.
type InfoResponse struct {
	messageNoReflect
	Name       string
	Version    string
	Kind       string
	Ready      bool
	MemoryMB   int64
	DeviceType string
}

// Reset implements proto.Message.
func (m *InfoResponse) Reset() { *m = InfoResponse{} }

// String implements proto.Message.
func (m *InfoResponse) String() string { return fmt.Sprintf("InfoResponse{name:%s}", m.Name) }

// ProtoMessage implements proto.Message.
func (*InfoResponse) ProtoMessage() {}

// ProtoReflect implements proto.Message.
func (m *InfoResponse) ProtoReflect() protoreflect.Message { return nil }

// Compile-time interface checks for all proto messages.
var (
	_ proto.Message = (*ClassifyRequest)(nil)
	_ proto.Message = (*TraceGroup)(nil)
	_ proto.Message = (*Trace)(nil)
	_ proto.Message = (*ClassifyResponse)(nil)
	_ proto.Message = (*Flow)(nil)
	_ proto.Message = (*PingRequest)(nil)
	_ proto.Message = (*PingResponse)(nil)
	_ proto.Message = (*InfoRequest)(nil)
	_ proto.Message = (*InfoResponse)(nil)
)
