#!/usr/bin/env python3
"""Append dogfood findings DF-027..DF-032 to the rabbit-hole board (v2.1 JSONL)."""
import json
from datetime import datetime, timezone

now = datetime.now(timezone.utc).isoformat()

tasks = [
    {
        "id": "DF-027",
        "title": "🔴 P0 — serve daemon wedges under documented use: 19.7GB RSS / 681% CPU in ~15 min, HTTP unresponsive, demo stream halts, SIGQUIT cannot kill (needs SIGKILL). Dogfood run 2026-08-18: `serve --no-ebpf --demo-stream --remote 127.0.0.1:50051@secret` + 4 attach/detach cycles + WS client connect/disconnect + `demo --spread` seed on same DB. At ~05:24:56 the last 'demo stream: flow published' line appears, then total silence; /health, /api/v1/sessions, /api/v1/stats all time out (000); /proc/<pid>/status shows VmRSS 19766380 kB, Threads 22; `kill -QUIT` started a goroutine dump but the process never exited (stack shows main goroutine parked on chan receive); SIGKILL required. A second daemon on the same SQLite DB (no demo-stream, no remote) stayed healthy — wedge is specific to the demo-stream/remote/WS/attach combo. Data survived SIGKILL (WAL, integrity_check ok, 13 sessions / 283 flows intact). For a 24/7 agent-watcher this is the worst failure mode: collection stops SILENTLY. FIX: reproduce with a bounded soak (demo-stream + remote + WS subscriber + attach cycles), find the leak/spin (suspects: remote gRPC client retry loop, WS hub buffering for disconnected subscribers, SQLite busy-spin), add a soak test with RSS/CPU assertions, and ensure SIGQUIT always terminates. PASS: 30-min soak of the documented Quick Start (serve --demo-stream + remote + WS + attach) keeps RSS < 500MB, /health answers < 1s throughout, and SIGQUIT exits the process.",
        "status": "pending",
        "priority": "P0",
        "complexity": 3,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18 (real use, 55 min): wedge observed live — VmRSS 19766380 kB, 681% CPU, all HTTP 000, demo stream silent after 05:24:56.659, SIGQUIT ineffective. Restart on same DB recovered cleanly (data intact).",
        "capability_tags": ["reliability", "daemon", "memory", "soak"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
    {
        "id": "DF-028",
        "title": "🟡 P1 — session lifecycle unreliable in degraded (--no-ebpf) mode: (a) an attached process that exits naturally (sleep 30, exit 0) leaves its session 'running' indefinitely — verified 3+ min after process death via GET /api/v1/sessions, no transition ever observed; (b) an earlier session (sleep 300) showed status 'crashed' with end_time 14s after attach while the process was still alive — trigger not reproduced (dup-attach 409, demo --spread seed, natural exit all tested clean individually). For a legibility product the session status IS the product: ghost 'running' sessions and false 'crashed' labels mislead the human this tool exists for. FIX: add a process-exit monitor for degraded attach sessions (procfs poll or waitpid in the daemon) that transitions to a terminal state with an honest label (exit-0 vs signal), and unit-test the transition within a bounded time. PASS: attach --no-ebpf to `sleep 30` → session transitions to a terminal status (completed/crashed) within 60s of process exit with correct label; attach to a long-lived process stays 'running' for 10+ min.",
        "status": "pending",
        "priority": "P1",
        "complexity": 2,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18: sleep-30 session still 'running' 80+s after exit (checked 3x); sleep-300 session 'crashed' at end_time 05:15:11, 14s after attach, while ps showed the process alive; DB ground truth via sqlite3.",
        "capability_tags": ["sessions", "collector", "cli"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
    {
        "id": "DF-029",
        "title": "🟢 P2 — `compact --before 10m` rejected: 'invalid duration \"10m\": unsupported duration suffix: m (use h or d)' (exit 1). Minutes are the most natural unit for compaction; README and --help only ever show h/d examples (`-30d`, `-720h`), so a user learns the suffix whitelist only by hitting the error. FIX: accept m (and s) suffixes in the duration parser, or expand the error/help to list supported suffixes with examples. PASS: `compact --before 10m` runs (or the error message lists exactly which suffixes are accepted, e.g. 'use s, m, h or d').",
        "status": "pending",
        "priority": "P2",
        "complexity": 1,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18: `compact --before 10m` on a scratch DB copy → error, exit 1; `compact --before 1h` works. README Quick Start shows only `--before 720h`.",
        "capability_tags": ["cli", "ux"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
    {
        "id": "DF-030",
        "title": "🟢 P3 — `demo`'s 'Next:' hint prints the default addr, not the running daemon's: with `serve --addr 127.0.0.1:19734` running, `demo --flows 20` prints 'Next: run `rabbit-hole serve` and open http://localhost:9734/dashboard' (default port, no trailing-slash note). demo has no --addr flag and only honors RABBITHOLE_LISTEN_ADDR env, so the hint is stale whenever the daemon runs on a non-default port (which --addr exists precisely to allow). FIX: read RABBITHOLE_LISTEN_ADDR for the hint (it already does via cfg — verify) or drop the URL from demo output. PASS: with RABBITHOLE_LISTEN_ADDR=127.0.0.1:19734 set, demo output references 19734; or demo prints no URL.",
        "status": "pending",
        "priority": "P3",
        "complexity": 1,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18: demo output showed :9734 while daemon ran on :19734 (verified in same shell, no env var set). DF-004 fixed the same class of bug for the default case; this is the env/flag variant.",
        "capability_tags": ["cli", "docs", "ux"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
    {
        "id": "DF-031",
        "title": "🟢 P3 — `attach` success message can print a wrong DB path: 'Session persisted to /home/kara/.rabbit-hole/rabbit-hole.db' is computed from the CLI's own config, not the daemon's — with RABBITHOLE_DB_PATH set for serve but not for the CLI, the printed path is fiction (verified: daemon DB was /tmp/dogfood-rabbit-hole/rh.db, message named ~/.rabbit-hole/rabbit-hole.db). FIX: reword to 'persisted via daemon' (no path), or have the attach API return the server's db_path and print that. PASS: attach output either contains no DB path or the path matches the serving daemon's RABBITHOLE_DB_PATH.",
        "status": "pending",
        "priority": "P3",
        "complexity": 1,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18: attach output claimed ~/.rabbit-hole/rabbit-hole.db while GET /api/v1/stats showed db_path /tmp/dogfood-rabbit-hole/rh.db. Cosmetic but actively misleading in mixed-env setups (DF-014 fixed the data path; this is the message path).",
        "capability_tags": ["cli", "ux"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
    {
        "id": "DF-032",
        "title": "🟢 P3 — demo-stream sessions are 'completed' with end_time NULL: GET /api/v1/sessions and the DB show status=completed but end_time=null for every demo session (verified in sqlite3: sessions 01a01459-f0b9, 01a0145d-86c8, 01a0145d-f6b6). A completed session with no end time is contradictory data — dashboards/consumers that compute duration get garbage. FIX: set end_time when marking demo sessions completed (or use a distinct status like 'demo'). PASS: all sessions with status=completed have non-null end_time in the API.",
        "status": "pending",
        "priority": "P3",
        "complexity": 1,
        "depends_on": None,
        "blocks": None,
        "primary_model": "deepseek-v4-flash",
        "primary_provider": "deepseek",
        "fallback_model": None,
        "fallback_provider": None,
        "reasoning": "Dogfood run 2026-08-18: sqlite3 query of the live demo DB showed 3 completed sessions, all end_time=None; API returns end_time null for them.",
        "capability_tags": ["storage", "api"],
        "worker_status": "pending",
        "dispatched_at": None,
        "completed_at": None,
        "attempts": 0,
        "exit_code": None,
        "commit_hash": None,
        "files_changed": None,
        "lines_added": None,
        "lines_removed": None,
        "guard_result": None,
        "ci_result": None,
        "worker_summary": None,
        "foreman_note": None,
        "blocked_reason": None,
        "review_notes": None,
        "created_at": now,
        "updated_at": now,
        "blocked_since": None,
    },
]

path = ".coding-hermes/board/tasks.jsonl"
with open(path, "a") as f:
    for t in tasks:
        f.write(json.dumps(t, ensure_ascii=False) + "\n")
print(f"appended {len(tasks)} tasks to {path}")

# verify
with open(path) as f:
    ids = [json.loads(l)["id"] for l in f if l.strip()]
print("last ids:", ids[-8:])
