// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents             = "events"
	bpfMapPidFilter          = "pid_filter"
	bpfMapStackMap           = "stack_map"
	bpfMapSyscallStart       = "syscall_start"
	bpfProgTraceClose        = "trace_close"
	bpfProgTraceConnect      = "trace_connect"
	bpfProgTraceEnterSyscall = "trace_enter_syscall"
	bpfProgTraceExec         = "trace_exec"
	bpfProgTraceExit         = "trace_exit"
	bpfProgTraceExitSyscall  = "trace_exit_syscall"
	bpfProgTraceFork         = "trace_fork"
	bpfProgTraceOpenat       = "trace_openat"
	bpfProgTraceRead         = "trace_read"
	bpfProgTraceRecvmsg      = "trace_recvmsg"
	bpfProgTraceSendmsg      = "trace_sendmsg"
	bpfProgTraceWrite        = "trace_write"
	bpfProgUprobeSslRead     = "uprobe_ssl_read"
	bpfProgUprobeSslWrite    = "uprobe_ssl_write"
	bpfProgUretprobeSslRead  = "uretprobe_ssl_read"
	bpfProgUretprobeSslWrite = "uretprobe_ssl_write"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceClose        *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceConnect      *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceEnterSyscall *ebpf.ProgramSpec `ebpf:"trace_enter_syscall"`
	TraceExec         *ebpf.ProgramSpec `ebpf:"trace_exec"`
	TraceExit         *ebpf.ProgramSpec `ebpf:"trace_exit"`
	TraceExitSyscall  *ebpf.ProgramSpec `ebpf:"trace_exit_syscall"`
	TraceFork         *ebpf.ProgramSpec `ebpf:"trace_fork"`
	TraceOpenat       *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceRead         *ebpf.ProgramSpec `ebpf:"trace_read"`
	TraceRecvmsg      *ebpf.ProgramSpec `ebpf:"trace_recvmsg"`
	TraceSendmsg      *ebpf.ProgramSpec `ebpf:"trace_sendmsg"`
	TraceWrite        *ebpf.ProgramSpec `ebpf:"trace_write"`
	UprobeSslRead     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeSslRead  *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslWrite *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	PidFilter    *ebpf.MapSpec `ebpf:"pid_filter"`
	StackMap     *ebpf.MapSpec `ebpf:"stack_map"`
	SyscallStart *ebpf.MapSpec `ebpf:"syscall_start"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	PidFilter    *ebpf.Map `ebpf:"pid_filter"`
	StackMap     *ebpf.Map `ebpf:"stack_map"`
	SyscallStart *ebpf.Map `ebpf:"syscall_start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.PidFilter,
		m.StackMap,
		m.SyscallStart,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceClose        *ebpf.Program `ebpf:"trace_close"`
	TraceConnect      *ebpf.Program `ebpf:"trace_connect"`
	TraceEnterSyscall *ebpf.Program `ebpf:"trace_enter_syscall"`
	TraceExec         *ebpf.Program `ebpf:"trace_exec"`
	TraceExit         *ebpf.Program `ebpf:"trace_exit"`
	TraceExitSyscall  *ebpf.Program `ebpf:"trace_exit_syscall"`
	TraceFork         *ebpf.Program `ebpf:"trace_fork"`
	TraceOpenat       *ebpf.Program `ebpf:"trace_openat"`
	TraceRead         *ebpf.Program `ebpf:"trace_read"`
	TraceRecvmsg      *ebpf.Program `ebpf:"trace_recvmsg"`
	TraceSendmsg      *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceWrite        *ebpf.Program `ebpf:"trace_write"`
	UprobeSslRead     *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite    *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeSslRead  *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslWrite *ebpf.Program `ebpf:"uretprobe_ssl_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceClose,
		p.TraceConnect,
		p.TraceEnterSyscall,
		p.TraceExec,
		p.TraceExit,
		p.TraceExitSyscall,
		p.TraceFork,
		p.TraceOpenat,
		p.TraceRead,
		p.TraceRecvmsg,
		p.TraceSendmsg,
		p.TraceWrite,
		p.UprobeSslRead,
		p.UprobeSslWrite,
		p.UretprobeSslRead,
		p.UretprobeSslWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
