// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/classifier/v1/classifier.proto

package classifierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Classifier_Classify_FullMethodName = "/classifier.v1.Classifier/Classify"
	Classifier_Ping_FullMethodName     = "/classifier.v1.Classifier/Ping"
	Classifier_Info_FullMethodName     = "/classifier.v1.Classifier/Info"
)

// ClassifierClient is the client API for Classifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Classifier is a remote classification service for Rabbit-Hole trace groups.
type ClassifierClient interface {
	// Classify turns trace groups into semantic flows.
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	// Ping is a lightweight health check.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Info returns model and runtime metadata.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type classifierClient struct {
	cc grpc.ClientConnInterface
}

func NewClassifierClient(cc grpc.ClientConnInterface) ClassifierClient {
	return &classifierClient{cc}
}

func (c *classifierClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, Classifier_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Classifier_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classifierClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Classifier_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassifierServer is the server API for Classifier service.
// All implementations must embed UnimplementedClassifierServer
// for forward compatibility.
//
// Classifier is a remote classification service for Rabbit-Hole trace groups.
type ClassifierServer interface {
	// Classify turns trace groups into semantic flows.
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	// Ping is a lightweight health check.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Info returns model and runtime metadata.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedClassifierServer()
}

// UnimplementedClassifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassifierServer struct{}

func (UnimplementedClassifierServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedClassifierServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClassifierServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedClassifierServer) mustEmbedUnimplementedClassifierServer() {}
func (UnimplementedClassifierServer) testEmbeddedByValue()                    {}

// UnsafeClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassifierServer will
// result in compilation errors.
type UnsafeClassifierServer interface {
	mustEmbedUnimplementedClassifierServer()
}

func RegisterClassifierServer(s grpc.ServiceRegistrar, srv ClassifierServer) {
	// If the following call panics, it indicates UnimplementedClassifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Classifier_ServiceDesc, srv)
}

func _Classifier_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classifier_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classifier_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classifier_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classifier_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassifierServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Classifier_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassifierServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Classifier_ServiceDesc is the grpc.ServiceDesc for Classifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Classifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classifier.v1.Classifier",
	HandlerType: (*ClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _Classifier_Classify_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Classifier_Ping_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Classifier_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/classifier/v1/classifier.proto",
}
