// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/classifier/v1/classifier.proto

package classifierpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*TraceGroup          `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetGroups() []*TraceGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type TraceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*Trace               `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceGroup) Reset() {
	*x = TraceGroup{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceGroup) ProtoMessage() {}

func (x *TraceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceGroup.ProtoReflect.Descriptor instead.
func (*TraceGroup) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *TraceGroup) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Syscall       string                 `protobuf:"bytes,2,opt,name=syscall,proto3" json:"syscall,omitempty"`
	Args          string                 `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	ReturnValue   int64                  `protobuf:"varint,4,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{2}
}

func (x *Trace) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Trace) GetSyscall() string {
	if x != nil {
		return x.Syscall
	}
	return ""
}

func (x *Trace) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *Trace) GetReturnValue() int64 {
	if x != nil {
		return x.ReturnValue
	}
	return 0
}

func (x *Trace) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*Flow                `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *ClassifyResponse) GetFlows() []*Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Outcome       string                 `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TraceIds      []string               `protobuf:"bytes,7,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	StartTime     int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationNs    int64                  `protobuf:"varint,10,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{4}
}

func (x *Flow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flow) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *Flow) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Flow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flow) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Flow) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Flow) GetTraceIds() []string {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

func (x *Flow) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Flow) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Flow) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{5}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{6}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{7}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DeviceType    string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_classifier_v1_classifier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_classifier_v1_classifier_proto_rawDescGZIP(), []int{8}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InfoResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *InfoResponse) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *InfoResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

var File_api_proto_classifier_v1_classifier_proto protoreflect.FileDescriptor

const file_api_proto_classifier_v1_classifier_proto_rawDesc = "" +
	"\n" +
	"(api/proto/classifier/v1/classifier.proto\x12\rclassifier.v1\"D\n" +
	"\x0fClassifyRequest\x121\n" +
	"\x06groups\x18\x01 \x03(\v2\x19.classifier.v1.TraceGroupR\x06groups\":\n" +
	"\n" +
	"TraceGroup\x12,\n" +
	"\x06traces\x18\x01 \x03(\v2\x14.classifier.v1.TraceR\x06traces\"\x8d\x01\n" +
	"\x05Trace\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\asyscall\x18\x02 \x01(\tR\asyscall\x12\x12\n" +
	"\x04args\x18\x03 \x01(\tR\x04args\x12!\n" +
	"\freturn_value\x18\x04 \x01(\x03R\vreturnValue\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs\"=\n" +
	"\x10ClassifyResponse\x12)\n" +
	"\x05flows\x18\x01 \x03(\v2\x13.classifier.v1.FlowR\x05flows\"\x98\x02\n" +
	"\x04Flow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aoutcome\x18\x05 \x01(\tR\aoutcome\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\ttrace_ids\x18\a \x03(\tR\btraceIds\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\x03R\aendTime\x12\x1f\n" +
	"\vduration_ns\x18\n" +
	" \x01(\x03R\n" +
	"durationNs\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\r\n" +
	"\vInfoRequest\"\xa4\x01\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x03R\bmemoryMb\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType2\xdb\x01\n" +
	"\n" +
	"Classifier\x12K\n" +
	"\bClassify\x12\x1e.classifier.v1.ClassifyRequest\x1a\x1f.classifier.v1.ClassifyResponse\x12?\n" +
	"\x04Ping\x12\x1a.classifier.v1.PingRequest\x1a\x1b.classifier.v1.PingResponse\x12?\n" +
	"\x04Info\x12\x1a.classifier.v1.InfoRequest\x1a\x1b.classifier.v1.InfoResponseBTZRgitlab.readydedis.com/rabbit-hole/rabbit-hole/api/proto/classifier/v1;classifierpbb\x06proto3"

var (
	file_api_proto_classifier_v1_classifier_proto_rawDescOnce sync.Once
	file_api_proto_classifier_v1_classifier_proto_rawDescData []byte
)

func file_api_proto_classifier_v1_classifier_proto_rawDescGZIP() []byte {
	file_api_proto_classifier_v1_classifier_proto_rawDescOnce.Do(func() {
		file_api_proto_classifier_v1_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_classifier_v1_classifier_proto_rawDesc), len(file_api_proto_classifier_v1_classifier_proto_rawDesc)))
	})
	return file_api_proto_classifier_v1_classifier_proto_rawDescData
}

var file_api_proto_classifier_v1_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_classifier_v1_classifier_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: classifier.v1.ClassifyRequest
	(*TraceGroup)(nil),       // 1: classifier.v1.TraceGroup
	(*Trace)(nil),            // 2: classifier.v1.Trace
	(*ClassifyResponse)(nil), // 3: classifier.v1.ClassifyResponse
	(*Flow)(nil),             // 4: classifier.v1.Flow
	(*PingRequest)(nil),      // 5: classifier.v1.PingRequest
	(*PingResponse)(nil),     // 6: classifier.v1.PingResponse
	(*InfoRequest)(nil),      // 7: classifier.v1.InfoRequest
	(*InfoResponse)(nil),     // 8: classifier.v1.InfoResponse
}
var file_api_proto_classifier_v1_classifier_proto_depIdxs = []int32{
	1, // 0: classifier.v1.ClassifyRequest.groups:type_name -> classifier.v1.TraceGroup
	2, // 1: classifier.v1.TraceGroup.traces:type_name -> classifier.v1.Trace
	4, // 2: classifier.v1.ClassifyResponse.flows:type_name -> classifier.v1.Flow
	0, // 3: classifier.v1.Classifier.Classify:input_type -> classifier.v1.ClassifyRequest
	5, // 4: classifier.v1.Classifier.Ping:input_type -> classifier.v1.PingRequest
	7, // 5: classifier.v1.Classifier.Info:input_type -> classifier.v1.InfoRequest
	3, // 6: classifier.v1.Classifier.Classify:output_type -> classifier.v1.ClassifyResponse
	6, // 7: classifier.v1.Classifier.Ping:output_type -> classifier.v1.PingResponse
	8, // 8: classifier.v1.Classifier.Info:output_type -> classifier.v1.InfoResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_classifier_v1_classifier_proto_init() }
func file_api_proto_classifier_v1_classifier_proto_init() {
	if File_api_proto_classifier_v1_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_classifier_v1_classifier_proto_rawDesc), len(file_api_proto_classifier_v1_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_classifier_v1_classifier_proto_goTypes,
		DependencyIndexes: file_api_proto_classifier_v1_classifier_proto_depIdxs,
		MessageInfos:      file_api_proto_classifier_v1_classifier_proto_msgTypes,
	}.Build()
	File_api_proto_classifier_v1_classifier_proto = out.File
	file_api_proto_classifier_v1_classifier_proto_goTypes = nil
	file_api_proto_classifier_v1_classifier_proto_depIdxs = nil
}
